services:
  server:
    build:
      context: .
      target: final
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=example
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
